version: '3'
services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: voucher_blog
      MYSQL_ROOT_PASSWORD: voucher-blog-secret
    ports:
    - "3306:3306"
    volumes:
      - ./test/data:/docker-entrypoint-initdb.d
    mem_limit: 512m
    networks:
      - app-network
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    command: npm start
  
networks:
  app-network:
    driver: bridge