version: '3'
services:
  db:
    image: mysql:8.1
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql-data:/var/lib/mysql
    mem_limit: 512m
    networks:
      - app-network
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env
    command:
      - sh
      - -c
      - |
        npx prisma generate
        until nc -z db 3306; do sleep 1; done
        npm start
  
networks:
  app-network:
    driver: bridge