version: '3'
services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: voucher-blog-secret
    ports:
    - "3306:3306"
    volumes:
      - /var/lib/mysql
    mem_limit: 512m
    networks:
      - app-network
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    command:
      - sh
      - -c
      - |
        npx prisma generate
        until nc -z db 3306; do sleep 1; done
        npm start
  studio:
    build: .
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - db
    networks:
      - app-network
    command:
      - sh
      - -c
      - |
        until nc -z db 3306; do sleep 1; done
        npx prisma db push --skip-generate
        npx prisma studio
  
networks:
  app-network:
    driver: bridge